language: objective-c
osx_image: xcode7

xcode_project: FAU FabLab.xcodeproj
xcode_scheme: FAU FabLab Release

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew install carthage
  - gem update --system
  - gem install fastlane

script:
  - carthage bootstrap
  - fastlane clean
  - fastlane build
  - fastlane test

